"""Purpose-aware retrieval planning, projection, and fusion primitives."""

from .adaptive_policy import (
    ADAPTIVE_POLICY_CONFIG_VERSION,
    DEFAULT_ADAPTIVE_RETRIEVAL_POLICY_CONFIG,
    AdaptiveQueryFeatures,
    AdaptiveRetrievalDecision,
    AdaptiveRetrievalPolicy,
    AdaptiveRetrievalPolicyConfig,
    GraphDecision,
    GraphHopEvidence,
    LaneRawEvidence,
)
from .dense import (
    DENSE_PROJECTION_ID,
    DENSE_PROJECTION_REVISION,
    DENSE_VECTOR_DIMENSIONS,
    dense_projection_signature,
)
from .fusion import RRF_K, relevance_reranked, weighted_rrf
from .graph import (
    GRAPH_LINK_TYPES,
    GRAPH_PROJECTION_ID,
    GRAPH_PROJECTION_VERSION,
    GRAPH_RELATION_WEIGHTS,
)
from .learned_reranking import (
    SWARMBRAIN_MEMORY_RERANK_SERIALIZER_REVISION,
    LearnedRerankValidationError,
    build_learned_rerank_request,
    build_learned_rerank_result,
    build_swarm_memory_rerank_request,
    canonical_memory_rerank_input,
    learned_score_reranked,
    make_learned_rerank_candidate,
    request_usage_dimensions,
    validate_learned_rerank_result,
)
from .packing import (
    MAX_FACILITY_CANDIDATES,
    AnswerInContextMetrics,
    PackedBundle,
    PackingFeatures,
    answer_in_context,
    build_packing_features,
    estimate_tokens,
    pack_to_budget,
    render_recall_hit,
)
from .planner import RetrievalPlanner, parse_query_identifiers
from .projection import (
    RETRIEVAL_PROJECTION_ID,
    domain_lane,
    exact_terms,
    lookup_text,
    projection_scope_key,
    search_text,
    trigram_similarity,
)
from .relevance import (
    RELEVANCE_VERSION,
    RelevanceQuery,
    candidate_relevance,
    relevance_query,
)
from .temporal_query import (
    TEMPORAL_QUERY_PARSER_VERSION,
    ClosedReferencedTime,
    ReferencedTimeInterval,
    TemporalConfidence,
    TemporalParseReason,
    TemporalParseStatus,
    TemporalQueryParse,
    parse_referenced_time,
)

__all__ = [
    "ADAPTIVE_POLICY_CONFIG_VERSION",
    "DEFAULT_ADAPTIVE_RETRIEVAL_POLICY_CONFIG",
    "RELEVANCE_VERSION",
    "AdaptiveQueryFeatures",
    "AdaptiveRetrievalDecision",
    "AdaptiveRetrievalPolicy",
    "AdaptiveRetrievalPolicyConfig",
    "AnswerInContextMetrics",
    "ClosedReferencedTime",
    "DENSE_PROJECTION_ID",
    "DENSE_PROJECTION_REVISION",
    "DENSE_VECTOR_DIMENSIONS",
    "GRAPH_LINK_TYPES",
    "GRAPH_PROJECTION_ID",
    "GRAPH_PROJECTION_VERSION",
    "GRAPH_RELATION_WEIGHTS",
    "GraphDecision",
    "GraphHopEvidence",
    "LaneRawEvidence",
    "LearnedRerankValidationError",
    "MAX_FACILITY_CANDIDATES",
    "RETRIEVAL_PROJECTION_ID",
    "RRF_K",
    "SWARMBRAIN_MEMORY_RERANK_SERIALIZER_REVISION",
    "ReferencedTimeInterval",
    "RelevanceQuery",
    "PackedBundle",
    "PackingFeatures",
    "RetrievalPlanner",
    "TemporalConfidence",
    "TemporalParseReason",
    "TemporalParseStatus",
    "TemporalQueryParse",
    "TEMPORAL_QUERY_PARSER_VERSION",
    "answer_in_context",
    "build_packing_features",
    "build_learned_rerank_request",
    "build_learned_rerank_result",
    "build_swarm_memory_rerank_request",
    "candidate_relevance",
    "canonical_memory_rerank_input",
    "domain_lane",
    "dense_projection_signature",
    "estimate_tokens",
    "exact_terms",
    "lookup_text",
    "learned_score_reranked",
    "make_learned_rerank_candidate",
    "pack_to_budget",
    "parse_query_identifiers",
    "parse_referenced_time",
    "projection_scope_key",
    "relevance_query",
    "relevance_reranked",
    "request_usage_dimensions",
    "render_recall_hit",
    "search_text",
    "trigram_similarity",
    "validate_learned_rerank_result",
    "weighted_rrf",
]
